### ISSUE TITLE
Update to OpenRefine 3.2

### ISSUE THREAD

**Issue by wetneb** [stkenny/Refine-NER-Extension#2]
For this extension to work with OpenRefine 3.2, the serialization of some classes will need to be migrated to Jackson instead of org.json. A migration guide is available here:
https://github.com/OpenRefine/OpenRefine/wiki/Migration-guide-for-extension-and-fork-maintainers

An example PR doing this for another extension can be found at https://github.com/stkenny/grefine-rdf-extension/pull/18.

**Comment by ernestorefinepro** [comment]
Hello, I will start to work on this issue

**Comment by wetneb** [comment]
Hi @ernestorefinepro, I think this has already been tackled by @stkenny. I'll close this issue.

**Comment by wetneb** [comment]
Ah sorry I thought this was about the RDF extension. Indeed this hasn't been done before! Reopening.

**Comment by ernestorefinepro** [comment]
Hello, the migration to Jackson it's almost complete. I am currently testing all the changes and reviewing the full extension. I will be creating a pull request early next year.
