### ISSUE TITLE
Unclear installation process or Open Refine does not recognise the extension

### ISSUE THREAD

**Issue by GO5IT** [stkenny/Refine-NER-Extension#3]
Hello,

This is excellent extension, so I really would like to use it, but somehow it does not start. Maybe you can help me?

I follow the instruction,  but it is not clear, while other extension (eg https://github.com/stkenny/grefine-rdf-extension/wiki) works fine with clear explanation. I guess the problem is the path to the extension files.

>     Compile the source code to the module directory.
>     Copy the module folder to your extensions folder.
> 
>     To find your extensions folder, choose Browse workspace directory from the Refine interface, and navigate to the folder extensions (which you should create if it doesn't exist yet).
> 
>     Start or restart Refine.
>     Open or create a project.
>     Click the Named-entity recognition button at the top, choose Configure services... and enter your API keys.

With another extension, I simply download it and unzip and put it under the right location without any modification (....AppData\Roaming\OpenRefine\extensions). The folder name is "rdf-extension" and it has "module" folder in it. After restart, it works very easily.

So, I try with your extension, but the unziped folder has a bit skeptical name: "Refine-NER-Extension-master". Within it, there are "module" folder as well as others ("src" folder and other files). What is expected to put in the "extensions" folder? I have tried several variations, but they failed. After opening a project, there is no Named-entity recognition button at the top. The installation explanation is not very clear. I don't know if the extension is still up-to-date and/or, installation process is still valid, but it is highly appreciated to clarify those. Thank you so much!

**Comment by stkenny** [comment]
That sounds like you downloaded the source code rather than the release version from https://github.com/stkenny/Refine-NER-Extension/releases/download/v1.5.1/ner-extension-1.5.1.zip
Note, this will only work with OpenRefine 3.1.

**Comment by GO5IT** [comment]
Ok thank you! I didn't know it only works with 3.1. I used 3.2. So, I tried again, but I cannot see anything new in the interface. Can you tell me what should be the name of the folder under "extensions" folder? it is not "module" as the zip provided above, right? I tried with "named-entity-recognition" and "ner-extension". But no success. I guess this is the problem. Cheers!

**Comment by stkenny** [comment]
The folder name doesn't matter, but the module directory should be in the folder, so
  extensions/ner/module

**Comment by GO5IT** [comment]
Hi @stkenny, thanks a lot. It worked. 

One more question if I may. Default DBpedia NER works, but this service works for other APIs, right? Dandelion API documentation also suggest it. But, I am not sure how to configure. In Stanford NLP and  NLP service URI, I put "https://api.dandelion.eu/datatxt/nex/v1/?lang=de&text=&include=types%2Cabstract%2Ccategories%2Cimage&token="  And, in Data Text, I put my API key in the API key part. It started normally, but after 100%, the new column was completely blank for all rows. What might go wrong in this case?

**Comment by stkenny** [comment]
The Stanford NLP configuration expects the endpoint of a Stanford NLP web service. It will not work with a different service. For Dandelion you should configure the dataTXT service. It looks like the authentication mechanism for Dandelion has changed to use a token. In the extension it needs the legacy api ID and key. I'm not sure if you can still get those.

**Comment by GO5IT** [comment]
Hello! Thank you.
Dandelion website says 

> However, we still support $app_id and $app_key authentication for applications and 
> integrations not yet migrated to the new mechanism. For example, if you are using the >OpenRefine` integration, use the token below for both $app_id and $app_key >parameters.

So, in principle it would work, no? 
Unfortunately a few trials gave me errors, saying "no such token". I am not sure if the input URI is correct or not. I put "https://api.dandelion.eu/datatxt/nex/v1/?token=" in APP ID and my API key in App key in the NER form. What would you think the right syntax here? (Or what should be the exact input in the case of legacy API key? Maybe I can guess the right syntax from that) Cheers,

**Comment by stkenny** [comment]
Based on that quote it looks like you should put the token in both the APP ID and API Key fields. There isn't a field for setting a URI for Dandelion.

**Comment by GO5IT** [comment]
Ok. Actually, with the browser, the following syntax works (note: token is omitted):
https://api.dandelion.eu/datatxt/nex/v1/?lang=en&text=London+is+in+England&token=
So, one time is enough to put the token.

>There isn't a field for setting a URI for Dandelion.

What do you mean?

**Comment by GO5IT** [comment]
Sorry, I tried myself and it works! I put the token for both API ID and API Key fields. Thanks so much for your prompt support!
